.TH netctl-gui 1  "@CURRENT_DATE@" "version @PROJECT_VERSION@" "USER COMMANDS"
.SH NAME
netctl-gui is a graphical interface for netctl
.SH SYNOPSIS
.B netctl-gui
[ options ]
.SH DESCRIPTION
Graphical user interface for netctl written on C++ using Qt toolkit. Provides shared library for interaction with netctl and Plasmoid and DataEngine for KDE.
.SH OPTIONS
.TP
--daemon
run as daemon
.TP
--maximized
run maximized
.TP
--minimized
run to system tray if it is available
.TP
--about
show about window
.TP
--netctl-auto
show netctl-auto window
.TP
--settings
show settings window
.TP
-e, --essid ESSID
select ESSID ESSID. This option will set tab to 3 automatically
.TP
-o, --open PROFILE
open profile PROFILE. This option will set tab to 2 automatically
.TP
-s, --select PROFILE
select profile PROFILE. This option will set tab to 1 automatically
.TP
-c, --config FILE
read configuration from file FILE
.TP
-d, --debug
print debug information
.TP
--default
start with default settings
.TP
--set-opts OPTIONS
set options OPTIONS for this run, comma separated. Example "LANGUAGE=en,NETCTL_PATH=/usr/bin/netctl"
.TP
-t, --tab NUM
open a tab with number NUM
.TP
-v, --version
show version and exit
.TP
-i, --info
show build information and exit
.TP
-h, --help
show this help and exit
.SH FILES
.TP
$HOME/.config/netctl-gui.conf
Configuration file
.SH AUTHOR
@PROJECT_AUTHOR@ <\fI@PROJECT_CONTACT@\fR>
.SH LICENSE
This software is licensed under @PROJECT_LICENSE@
